"""ajustar_tabelas_foco

Revision ID: 0ee2ecc93bd7
Revises: 552c25c4a80c
Create Date: 2026-05-30 11:14:28.289662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee2ecc93bd7'
down_revision: Union[str, Sequence[str], None] = '552c25c4a80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
