"""criando_estrutura_nuvem

Revision ID: 290b5cab3382
Revises: 
Create Date: 2026-06-16 13:50:34.567455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290b5cab3382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=254), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('current_date'), nullable=True),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('current_date'), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('produtos')
    # ### end Alembic commands ###
